name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install Pytest
        run: pip install pytest
      - name: Run tests with pytest
        run: |
          pipenv run test -v
